#!/bin/bash
set -euo pipefail

CONFIG_FILE="${BUILD_DIR:-openwrt}/.config"

sed -ri 's/CONFIG_TARGET_PREINIT_IP=.+/CONFIG_TARGET_PREINIT_IP=10.12.20.1/' "$CONFIG_FILE"
sed -ri 's/CONFIG_TARGET_PREINIT_BROADCAST=.+/CONFIG_TARGET_PREINIT_BROADCAST=10.12.20.255/' "$CONFIG_FILE"
